/**
 * Per-DTO parsers backed by `schemas.X.pick({...}).strip()` from
 * `src/shared/api/zod-schemas.ts` (generated by `openapi-zod-client`
 * from the API's live OpenAPI spec — see `scripts/gen-api-types.ts`).
 *
 * Pattern: each parser is a one-liner that
 *   1. picks only the fields the MCP port exposes
 *      (the `Pick<S["X"], …>` projection in `api-gateway.ts`),
 *   2. calls `.strip()` to drop unknown keys at the top level
 *      (the schemas use `.passthrough()` so a future API addition
 *      never breaks us at runtime; `.strip()` keeps the tool output
 *      JSON small),
 *   3. hands the result to {@link parseWithSchema} which converts
 *      `safeParse` failure into a typed `ApiError` and runtime-strips
 *      keys whose value is explicitly `undefined` (zod's encoding for
 *      `default-backed optional` fields), matching the
 *      `exactOptionalPropertyTypes: true` semantics of port DTOs.
 *
 * Each parser carries an explicit `Result<PortDtoType, ApiError>`
 * return-type annotation. The `as` cast at the end is runtime-safe
 * because `parseWithSchema` strips `undefined`-valued keys —
 * TypeScript just cannot see this transformation through `z.infer<>`.
 *
 * If the API drops or renames a field, schema regen + tsc surfaces
 * the drift here as a TS error on the `.pick({…})` mask. Runtime
 * drift surfaces as a typed `upstream` MCP error with the zod issue
 * message — never as an `undefined.id` crash.
 */

import type {
  AlertNotificationDestinationResponse,
  AlertStatsResponse,
  ApiError,
  ApiKeyCreatedResponse,
  BalanceTransactionResponse,
  BulkReplayResponse,
  CampaignOverridesResponse,
  DeliveryAttemptResponse,
  EventCatalogResponse,
  GroupActionResponse,
  InvoiceResponse,
  OrgResponse,
  PolicyEntryResponse,
  RoleResponse,
  RuleTestResponse,
  ScanTagResponse,
  UsagePeriodSummaryResponse,
  UsageResponse,
  UserResponse,
} from "../../../domain/ports/api-gateway.js";
import { schemas } from "../../../shared/api/zod-schemas.js";
import { err, ok, type Result } from "../../../shared/result.js";
import { parsePagedWithItemSchema, parseWithSchema } from "./parse-with-schema.js";

/**
 * Generic per-item paginated parser — kept for callers that need
 * an `(raw) => Result<PaginatedResponse<T>>` thunk (the legacy
 * `parsePageOf(parseItem)` shape). The item parser is decoupled from
 * the envelope so callers compose freely.
 */
export function parsePageOf<T>(parseItem: (raw: unknown) => Result<T, ApiError>): (
  raw: unknown
) => Result<
  {
    readonly items: readonly T[];
    readonly total: number;
    readonly page: number;
    readonly limit: number;
  },
  ApiError
> {
  return (raw) => {
    if (raw === null || typeof raw !== "object") {
      return err({ kind: "upstream", detail: "malformed page envelope" });
    }
    const r = raw as { items?: unknown; total?: unknown; page?: unknown; limit?: unknown };
    if (
      !Array.isArray(r.items) ||
      typeof r.total !== "number" ||
      typeof r.page !== "number" ||
      typeof r.limit !== "number"
    ) {
      return err({ kind: "upstream", detail: "page envelope: wrong field types" });
    }
    const out: T[] = [];
    for (const item of r.items) {
      const parsed = parseItem(item);
      if (parsed.isErr()) return err(parsed.error);
      out.push(parsed.value);
    }
    return ok({ items: out, total: r.total, page: r.page, limit: r.limit });
  };
}

/** Generic per-item array parser. */
export function parseArrayOf<T>(
  parseItem: (raw: unknown) => Result<T, ApiError>
): (raw: unknown) => Result<readonly T[], ApiError> {
  return (raw) => {
    if (!Array.isArray(raw)) return err({ kind: "upstream", detail: "expected array" });
    const out: T[] = [];
    for (const item of raw) {
      const r = parseItem(item);
      if (r.isErr()) return err(r.error);
      out.push(r.value);
    }
    return ok(out);
  };
}

// ── Per-DTO parsers ──────────────────────────────────────────────

const OrgSchema = schemas.OrgResponse.pick({
  id: true,
  name: true,
  owner_id: true,
  is_active: true,
  created_at: true,
}).strip();

export const parseOrg = (raw: unknown): Result<OrgResponse, ApiError> =>
  parseWithSchema(OrgSchema, raw, "org") as Result<OrgResponse, ApiError>;

const UserSchema = schemas.UserResponse.pick({
  id: true,
  email: true,
  name: true,
  role_name: true,
  is_active: true,
  created_at: true,
}).strip();

export const parseUser = (raw: unknown): Result<UserResponse, ApiError> =>
  parseWithSchema(UserSchema, raw, "user") as Result<UserResponse, ApiError>;

const RoleSchema = schemas.RoleResponse.pick({
  id: true,
  name: true,
  scope: true,
  is_system: true,
  permissions: true,
}).strip();

export const parseRole = (raw: unknown): Result<RoleResponse, ApiError> =>
  parseWithSchema(RoleSchema, raw, "role") as Result<RoleResponse, ApiError>;

const ApiKeyCreatedSchema = schemas.ApiKeyCreatedResponse.pick({
  id: true,
  key_prefix: true,
  full_key: true,
  name: true,
  expires_at: true,
  created_at: true,
}).strip();

export const parseApiKeyCreated = (raw: unknown): Result<ApiKeyCreatedResponse, ApiError> =>
  parseWithSchema(ApiKeyCreatedSchema, raw, "api-key-created") as Result<
    ApiKeyCreatedResponse,
    ApiError
  >;

const ScanTagSchema = schemas.ScanTagResponse.pick({
  id: true,
  scan_id: true,
  tag_slug: true,
  detail: true,
  url: true,
  display_name: true,
  category: true,
  severity: true,
  created_at: true,
}).strip();

export const parseScanTag = (raw: unknown): Result<ScanTagResponse, ApiError> =>
  parseWithSchema(ScanTagSchema, raw, "scan-tag") as Result<ScanTagResponse, ApiError>;

const RuleTestSchema = schemas.RuleTestResponse.pick({
  matched: true,
  elapsed_ms: true,
  tags: true,
}).strip();

export const parseRuleTest = (raw: unknown): Result<RuleTestResponse, ApiError> =>
  parseWithSchema(RuleTestSchema, raw, "rule-test") as Result<RuleTestResponse, ApiError>;

const AlertStatsSchema = schemas.AlertStatsResponse.pick({
  open: true,
  acknowledged: true,
  resolved: true,
  dismissed: true,
}).strip();

export const parseAlertStats = (raw: unknown): Result<AlertStatsResponse, ApiError> =>
  parseWithSchema(AlertStatsSchema, raw, "alert-stats") as Result<AlertStatsResponse, ApiError>;

const UsageSchema = schemas.UsageResponse.pick({
  id: true,
  scan_id: true,
  charged_micros: true,
  balance_after_micros: true,
  within_plan: true,
  event_type: true,
  created_at: true,
}).strip();

export const parseUsage = (raw: unknown): Result<UsageResponse, ApiError> =>
  parseWithSchema(UsageSchema, raw, "usage") as Result<UsageResponse, ApiError>;

const UsageSummarySchema = schemas.UsagePeriodSummaryResponse.pick({
  period_start: true,
  period_end: true,
  checks: true,
  rechecks: true,
  within_plan: true,
  overage: true,
  charged_micros: true,
}).strip();

export const parseUsageSummary = (raw: unknown): Result<UsagePeriodSummaryResponse, ApiError> =>
  parseWithSchema(UsageSummarySchema, raw, "usage-summary") as Result<
    UsagePeriodSummaryResponse,
    ApiError
  >;

const BalanceTxSchema = schemas.BalanceTransactionResponse.pick({
  id: true,
  type: true,
  amount_micros: true,
  balance_after_micros: true,
  description: true,
  reference_kind: true,
  reference_id: true,
  actor_user_id: true,
  created_at: true,
}).strip();

export const parseBalanceTx = (raw: unknown): Result<BalanceTransactionResponse, ApiError> =>
  parseWithSchema(BalanceTxSchema, raw, "balance-tx") as Result<
    BalanceTransactionResponse,
    ApiError
  >;

const InvoiceSchema = schemas.InvoiceResponse.pick({
  id: true,
  number: true,
  type: true,
  status: true,
  total_micros: true,
  currency: true,
  period_start: true,
  period_end: true,
  issued_at: true,
  paid_at: true,
  voided_at: true,
  has_pdf: true,
  description: true,
  payment_method: true,
  created_at: true,
}).strip();

export const parseInvoice = (raw: unknown): Result<InvoiceResponse, ApiError> =>
  parseWithSchema(InvoiceSchema, raw, "invoice") as Result<InvoiceResponse, ApiError>;

const WebhookDeliverySchema = schemas.DeliveryAttemptResponse.pick({
  id: true,
  event_id: true,
  event_type: true,
  response_status: true,
  success: true,
  attempt_number: true,
  error_code: true,
  elapsed_ms: true,
  created_at: true,
}).strip();

export const parseWebhookDelivery = (raw: unknown): Result<DeliveryAttemptResponse, ApiError> =>
  parseWithSchema(WebhookDeliverySchema, raw, "webhook-delivery") as Result<
    DeliveryAttemptResponse,
    ApiError
  >;

const EventCatalogSchema = schemas.EventCatalogResponse.pick({
  entries: true,
}).strip();

export const parseEventCatalog = (raw: unknown): Result<EventCatalogResponse, ApiError> =>
  parseWithSchema(EventCatalogSchema, raw, "event-catalog") as Result<
    EventCatalogResponse,
    ApiError
  >;

const AlertDestinationSchema = schemas.AlertNotificationDestinationResponse.pick({
  id: true,
  channel: true,
  name: true,
  is_active: true,
  is_default_target: true,
  version: true,
  consecutive_failures: true,
  last_delivery_at: true,
  last_delivery_status: true,
  slack_workspace_id: true,
  slack_channel_name: true,
  telegram_chat_title: true,
  telegram_chat_type: true,
  email_address: true,
  included_label_keys: true,
  created_at: true,
  updated_at: true,
}).strip();

export const parseAlertDestination = (
  raw: unknown
): Result<AlertNotificationDestinationResponse, ApiError> =>
  parseWithSchema(AlertDestinationSchema, raw, "alert-destination") as Result<
    AlertNotificationDestinationResponse,
    ApiError
  >;

const CampaignOverridesSchema = schemas.CampaignOverridesResponse.pick({
  campaign_id: true,
  mode: true,
  destination_ids: true,
}).strip();

export const parseCampaignAlertOverrides = (
  raw: unknown
): Result<CampaignOverridesResponse, ApiError> =>
  parseWithSchema(CampaignOverridesSchema, raw, "campaign-overrides") as Result<
    CampaignOverridesResponse,
    ApiError
  >;

const BulkReplaySchema = schemas.BulkReplayResponse.pick({
  replayed: true,
  skipped: true,
}).strip();

export const parseBulkReplay = (raw: unknown): Result<BulkReplayResponse, ApiError> =>
  parseWithSchema(BulkReplaySchema, raw, "bulk-replay") as Result<BulkReplayResponse, ApiError>;

const GroupActionSchema = schemas.GroupActionResponse.pick({
  group_id: true,
  affected_campaigns: true,
  cancelled_count: true,
  run_ids: true,
  failures: true,
}).strip();

export const parseGroupAction = (raw: unknown): Result<GroupActionResponse, ApiError> =>
  parseWithSchema(GroupActionSchema, raw, "group-action") as Result<GroupActionResponse, ApiError>;

const PolicyEntrySchema = schemas.PolicyEntryResponse.pick({
  id: true,
  tag_slug: true,
  country_codes: true,
}).strip();

export const parsePolicyEntry = (raw: unknown): Result<PolicyEntryResponse, ApiError> =>
  parseWithSchema(PolicyEntrySchema, raw, "policy-entry") as Result<PolicyEntryResponse, ApiError>;

// `parsePagedWithItemSchema` re-exported for callers using schema-based
// item validation directly.
export { parsePagedWithItemSchema };
